CREATE TABLE public.company
(
    id   bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name character varying(50)
);

CREATE TABLE public.profile
(
    id           bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name   character varying(100),
    last_name    character varying(100),
    created_date timestamp without time zone,
    company_id   bigint
);

CREATE TABLE public.initiative
(
    id                     bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title                  character varying(100),
    street_name            character varying(100),
    city                   character varying(50),
    postal_code            character varying(20),
    country                character varying(2),
    coordinator_profile_id bigint
);

CREATE TABLE public.wish
(
    id                   bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status               character varying(50),
    created_date         timestamp WITH time zone,
    volunteer_profile_id bigint,
    initiative_id        bigint
);

ALTER TABLE public.profile
    ADD FOREIGN KEY (company_id)
        REFERENCES public.company (id);

ALTER TABLE public.initiative
    ADD FOREIGN KEY (coordinator_profile_id)
        REFERENCES public.profile (id);

ALTER TABLE public.wish
    ADD FOREIGN KEY (volunteer_profile_id)
        REFERENCES public.profile (id);

ALTER TABLE public.wish
    ADD FOREIGN KEY (initiative_id)
        REFERENCES public.profile (id);
