spring:
    datasource:
        url: jdbc:h2:mem:wenabi;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        username: sa
        password: password
        driverClassName: org.h2.Driver
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        defer-datasource-initialization: false

        hibernate:
            ddl-auto: none
        h2:
            console.enabled: true
    sql:
        init:
            data-locations: classpath:data.sql
            schema-locations: classpath:schema.sql
            platform: h2
            mode: always

